# Generated by Django 4.0.5 on 2022-07-06 06:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='学号/工号'),
        ),
    ]
