# Generated by Django 4.0.5 on 2022-07-06 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0002_remove_user_num_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('credit', models.FloatField(verbose_name='课程学分')),
            ],
            options={
                'verbose_name': '课程',
            },
        ),
        migrations.CreateModel(
            name='EduClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_begin', models.IntegerField(verbose_name='开始周')),
                ('week_end', models.IntegerField(verbose_name='结束周')),
                ('begin_in_day', models.IntegerField(verbose_name='开始节数')),
                ('end_in_day', models.IntegerField(verbose_name='结束节数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.course', verbose_name='对应课程')),
            ],
            options={
                'verbose_name': '教学班',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.IntegerField(choices=[(0, '学生'), (1, '老师'), (2, '管理员')], default=0, null=True, verbose_name='身份'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('content', models.CharField(max_length=1000, verbose_name='作业要求')),
                ('educlass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.educlass', verbose_name='对应教学班')),
            ],
            options={
                'verbose_name': '作业',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('educlass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.educlass', verbose_name='对应教学班')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='对应学生')),
            ],
            options={
                'verbose_name': '分数',
            },
        ),
        migrations.CreateModel(
            name='PeopleClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('educlass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.educlass', verbose_name='对应教学班')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '教学班人员',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='create_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建老师'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作业完成者')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.work', verbose_name='对应作业')),
            ],
            options={
                'verbose_name': '作业提交',
            },
        ),
    ]
