# Generated by Django 4.0.5 on 2022-07-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0003_course_educlass_alter_user_identity_work_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educlass',
            name='whichday',
            field=models.IntegerField(default=0, verbose_name='星期几'),
            preserve_default=False,
        ),
    ]
