# Generated by Django 4.0.5 on 2022-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0004_educlass_whichday'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(default=1, max_length=1000, verbose_name='提交内容'),
            preserve_default=False,
        ),
    ]
