# Generated by Django 4.0.5 on 2022-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0005_answer_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.FloatField(default=1, verbose_name='最终分数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='score_final',
            field=models.FloatField(default=1, verbose_name='期末分数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='score_normal',
            field=models.FloatField(default=1, verbose_name='平时分数'),
            preserve_default=False,
        ),
    ]
