# Generated by Django 4.0.5 on 2022-07-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0006_score_score_score_score_final_score_score_normal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cls',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pls',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='专业'),
        ),
    ]
