# Generated by Django 4.0.5 on 2022-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0007_alter_user_cls_alter_user_pls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educlass',
            name='whichday',
            field=models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')], verbose_name='星期几'),
        ),
    ]
