# Generated by Django 4.0.5 on 2022-07-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0008_alter_educlass_whichday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buildingname', models.CharField(max_length=50, verbose_name='教学楼')),
                ('roomname', models.CharField(max_length=50, verbose_name='教室名')),
            ],
            options={
                'verbose_name': '教室',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='考试名')),
                ('begin_time', models.DateTimeField(verbose_name='考试开始时间')),
                ('end_time', models.DateTimeField(verbose_name='考试结束时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.classroom', verbose_name='考试所在教室')),
                ('educlass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edubackend.educlass', verbose_name='对应教学班')),
            ],
            options={
                'verbose_name': '考试',
            },
        ),
    ]
