# Generated by Django 4.0.5 on 2022-07-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0009_classroom_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='educlass',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edubackend.classroom', verbose_name='教学教室'),
        ),
    ]
