# Generated by Django 4.0.5 on 2022-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0010_educlass_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
