# Generated by Django 4.0.5 on 2022-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0011_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='educlass',
            name='xnm',
            field=models.CharField(default='2022-2023', max_length=50, verbose_name='学年名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educlass',
            name='xq',
            field=models.IntegerField(choices=[(1, '第一学期'), (2, '第二学期')], default=1, verbose_name='学期'),
            preserve_default=False,
        ),
    ]
