# Generated by Django 4.0.5 on 2022-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edubackend', '0012_educlass_xnm_educlass_xq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educlass',
            name='xnm',
            field=models.IntegerField(verbose_name='学年'),
        ),
    ]
